var SignUpSchema = {
    signup:{
        h1:{
            'name':'h1',
            'innerText':'SIGN UP',
            'id':'header'
        },
        form:{
            'name':'form',
            'id':'form',
            'onsubmit':'Flow.submitSignUpForm(event);',
            'elements':[
                {
                    'name':'input',
                    'type':'email',
                    'placeholder':'Email address',
                    'id':'emailid',
                    'required':'true',
                },
               {
                    'name':'input',
                    'type':'text',
                    'placeholder':'Username',
                    'id':'username',
                    'required':'true',
                },
               {
                    'name':'input',
                    'type':'password',
                    'placeholder':'Password',
                    'id':'password',
                    'required':'true',
                },
                {
                    'name':'input',
                    'type':'submit',
                    'value':'SIGN UP',
                    'id':'signup',
                }
            ]
        }
    }
}
var LoginSchema = {
    login:{
        h1:{
            'name':'h1',
            'innerText':'LOGIN',
            'id':'header'
        },
        form:{
            'name':'form',
            'id':'form',
            'onsubmit':'Flow.submitLoginForm(event);',
            'elements':[
                {
                    'name':'input',
                    'type':'email',
                    'placeholder':'Email address',
                    'id':'Remailid',
                    'required':'true',
                },
               {
                    'name':'input',
                    'type':'password',
                    'placeholder':'Password',
                    'id':'Rpassword',
                    'required':'true',
                },
                {
                    'name':'input',
                    'type':'submit',
                    'value':'LOGIN',
                    'id':'login',
                }
            ]
        }
    }  
}